src/views/login.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, session, abort
import time
import model_dto
import tools
import jwt
from forms import LoginForm, VerifyCodeForm, ResetPasswordForm

login_bp = Blueprint("login", __name__)  # Create a Blueprint for login-related routes

@login_bp.route("/", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        login_dto = model_dto.LoginDto(username=username, password=password)
        login_result = current_app.model.login(login_dto)

        if login_result == "True" or login_result == "verify_sms" or login_result == "verify_mail":
            flash("Login successful!", "success")
            #create session
            session["username"] = username
            user = current_app.model.get_user(username=username)
            session["user"] = user.dict()
            session["sms"] = current_app.model.get_registration_sms_code_from_user(user).dict()
            session["mail"] = current_app.model.get_registration_mail_code_from_user(user).dict()
            return redirect(url_for("login.dashboard"))
        else:
            flash(f"{login_result}", "danger")

    return render_template("login.html", form=form)

@login_bp.route("/dashboard")
def dashboard():
    username = session.get("username")
    return render_template("dashboard.html", username=username)

@login_bp.route("/logout")
def logout():
    session.clear()
    return redirect('/')

@login_bp.route("/admin")
def admin():
    if session.get("user")["role"] == "admin":
        return render_template("admin.html")
    else:
        session.clear()
        return redirect('/')

@login_bp.route("/reset", methods=["GET", "POST"])
def reset():
    form = ResetPasswordForm()
    if form.validate_on_submit():
        #check if user exists
        print("fetching user via mail:", form.mail.data)
        current_app.model.send_reset_mail(form.mail.data)
        flash("Reset mail sent!", "success")
        return redirect('/')
        pass
    return render_template("reset.html", form = form)

@login_bp.route("/reset_password", methods=["GET", "POST"])
def reset_password():
    if request.method == "POST":
        #get user input
        username = request.form.get("username")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        #get user
        user = current_app.model.get_user(username)

        if user.email != session.get("email"):
            print("invalid mail")
            flash(f"something went wrong", "danger")
            return redirect('/')

        if user:
            if password1 != password2:
                print("passwords do not match")
                flash("passwords do not match")
                return render_template("reset_password.html")
            #save new password
            user.password = password1
            current_app.model.update_user(user)
            return redirect('/')
        else:
            flash(f"something went wrong", "danger")

    #verify token
    token = request.args.get("token")
    if not token:
        abort(400, "Missing token")
    try:
        decoded_token = jwt.decode(token, "secret_key", algorithms=['HS256'])
        session["token"] = token
        session["email"] = decoded_token.get("email")
        return render_template("reset_password.html")
        print(decoded_token)
    except jwt.ExpiredSignatureError:
        flash("Token has expired")
        print("Token has expired")
        return redirect('/')
    except jwt.InvalidTokenError:
        print("Invalid token")
        flash("Invalid token")
        return redirect('/')

    return redirect('/')

@login_bp.route("/verify_code", methods=["GET", "POST"])
def verify_code():
    form = VerifyCodeForm()
    print(session.get("username"))
    verify_type = session.get("verify_type")
    label_text = f"{verify_type.capitalize()} code"  # 'sms code' or 'mail code'
    form.code.label.text = label_text

    if request.method == "POST" and form.validate_on_submit():
        user = session.get("user")
        code_under_under_test = model_dto.RegistrationCodeDto(code=form.code.data,
                                                              type=model_dto.CodeTypeEnum(verify_type),
                                                              user=model_dto.UserDto.model_validate(session.get("user"))
                                                              )
        print(code_under_under_test)
        if current_app.model.verify_registration_code(code_under_under_test) == True:
            username = session.get("username")
            user = current_app.model.get_user(username=username)
            session["user"] = user.dict()
            session["sms"] = current_app.model.get_registration_sms_code_from_user(user).dict()
            session["mail"] = current_app.model.get_registration_mail_code_from_user(user).dict()
            return redirect(url_for("login.dashboard"))
        else:
            flash("code incorrect", "danger")

    return render_template("verify_code.html", session = session, form = form)

src/views/register.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app
from pydantic import BaseModel, constr, EmailStr, ValidationError
import model_dto
from model_dto import UserDto
from forms import RegisterForm

register_bp = Blueprint("register", __name__)  # Create a Blueprint for registration-related routes

@register_bp.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        # Get form data
        form_data = {
            "username": form.username.data,
            "password": form.password.data,
            "email": form.email.data,
            "mobile_nr": form.mobile_nr.data
        }

        try:
            # Validate form data with Pydantic
            user = model_dto.UserDto.model_validate(form_data)
            result = current_app.model.register(user)
            # If valid, flash success and redirect (e.g., to a login page)
            if result:
               flash("Registration successful!", "success")
            else:
                flash("Registration failed!", "danger")
            return redirect('/')
        except ValidationError as e:
            # If validation fails, flash errors
            for error in e.errors():
                flash(f"{error['loc'][0]}: {error['msg']}", "danger")

    return render_template("register.html", form=form)

src/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
<div class="container mt-5">
    <h1>Welcome, {{ username }}!</h1>
    <p>This is your admin page.</p>

    <!-- Logout Link -->
    <a href="{{ url_for('login.logout') }}" id="logout-link" class="text-danger">Logout</a></div>
</body>
</html>

src/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
<div class="container mt-5">
    <h1>Welcome, {{ username }}!</h1>
    <p>This is your dashboard.</p>
    <p>This is your role: {{ session.user.role }}</p>

    <a href="{{ url_for('login.logout') }}" id="logout-link" class="text-danger">Logout</a>
    {% if session.user.role == "admin" %}
        <br>
        <a href="{{ url_for('login.admin') }}" id="admin-link" class="text-danger">Admin Page</a>
    {% endif %}
</div>
</body>
</html>

src/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container mt-5">
    <h2 class="text-center">Login</h2>
    <form method="POST" action="/">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.username.label(class_="form-label") }}
            {{ form.username(class_="form-control") }}
            {% for error in form.username.errors %}
                <small class="text-danger">{{ error }}</small>
            {% endfor %}
        </div>
        <div class="mb-3">
            {{ form.password.label(class_="form-label") }}
            {{ form.password(class_="form-control") }}
            {% for error in form.password.errors %}
                <small class="text-danger">{{ error }}</small>
            {% endfor %}
        </div>
        <div class="d-grid">
            {{ form.submit(class_="btn btn-primary") }}
        </div>
    </form>

    <br>
    <p>Don't have an account? <a href="{{ url_for('register.register') }}">Register here</a></p>
    <p>Forgot your password? <a href="{{ url_for('login.reset') }}">Reset here</a></p>

    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        <div class="mt-3">
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}
</div>
</body>
</html>

src/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>
        <form method="POST" action="{{ url_for('register.register') }}">
            {{ form.hidden_tag() }}

            <div class="mb-3">
                {{ form.username.label(class_="form-label") }}
                {{ form.username(class_="form-control") }}
                {% for error in form.username.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>

            <div class="mb-3">
                {{ form.password.label(class_="form-label") }}
                {{ form.password(class_="form-control") }}
                {% for error in form.password.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>

            <div class="mb-3">
                {{ form.email.label(class_="form-label") }}
                {{ form.email(class_="form-control") }}
                {% for error in form.email.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>

            <div class="mb-3">
                {{ form.mobile_nr.label(class_="form-label") }}
                {{ form.mobile_nr(class_="form-control") }}
                {% for error in form.mobile_nr.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>

            <div class="d-grid">
                {{ form.submit() }}
            </div>
        </form>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul>
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
</body>
</html>

src/templates/reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container mt-5">
    <h2 class="text-center">Reset Passwrd</h2>
    <form method="POST" action="/reset">
        {{ form.hidden_tag() }}
        <p>Please fill in your email.</p>
        <div class="mb-3">
            {{ form.mail.label(class_="form-label") }}
            {{ form.mail(class_="form-control") }}
            {% for error in form.mail.errors %}
                <small class="text-danger">{{ error }}</small>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Reset</button>
    </form>

    <br>

    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        <div class="mt-3">
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}
</div>
</body>
</html>

src/templates/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container mt-5">
    <h2 class="text-center">Reset Password</h2>
    <form method="POST" action="{{ url_for('login.reset_password') }}">
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" name="username" id="username" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="password1" class="form-label">Password1</label>
            <input type="text" name="password1" id="password1" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="password2" class="form-label">Password2</label>
            <input type="text" name="password2" id="password2" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Reset Password</button>
    </form>

    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        <div class="mt-3">
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}
</div>
</body>
</html>

src/templates/verify_code.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verify SMS</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container mt-5">
    <h2 class="text-center">Verify SMS</h2>
    <form method="POST" action="/verify_code">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            <p>Welcome {{ session["username"] }}<br>
            You still need to verify your {{ session["verify_type"] }} code</p>
            {{ form.code.label(class_="form-label") }}
            {{ form.code(class_="form-control") }}
            {% for error in form.code.errors %}
                <small class="text-danger">{{ error }}</small>
            {% endfor %}
        </div>
        <div class="d-grid">
            {{ form.submit() }}
        </div>
    </form>

    <br>
    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        <div class="mt-3">
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}
</div>
</body>
</html>